// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CreateFixedEffects
SEXP CreateFixedEffects(arma::uvec levelCounts, arma::mat indsR, arma::uvec simpleEffects, arma::uvec complexEffects, arma::uvec complexInfluences, List wrappedWeights);
RcppExport SEXP _fastplm_CreateFixedEffects(SEXP levelCountsSEXP, SEXP indsRSEXP, SEXP simpleEffectsSEXP, SEXP complexEffectsSEXP, SEXP complexInfluencesSEXP, SEXP wrappedWeightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type levelCounts(levelCountsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type indsR(indsRSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type simpleEffects(simpleEffectsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type complexEffects(complexEffectsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type complexInfluences(complexInfluencesSEXP);
    Rcpp::traits::input_parameter< List >::type wrappedWeights(wrappedWeightsSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateFixedEffects(levelCounts, indsR, simpleEffects, complexEffects, complexInfluences, wrappedWeights));
    return rcpp_result_gen;
END_RCPP
}
// ContainMultipleComponents
bool ContainMultipleComponents(SEXP wrappedFixedEffects);
RcppExport SEXP _fastplm_ContainMultipleComponents(SEXP wrappedFixedEffectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type wrappedFixedEffects(wrappedFixedEffectsSEXP);
    rcpp_result_gen = Rcpp::wrap(ContainMultipleComponents(wrappedFixedEffects));
    return rcpp_result_gen;
END_RCPP
}
// CheckComponents
List CheckComponents(SEXP wrappedFixedEffects, arma::mat indicators);
RcppExport SEXP _fastplm_CheckComponents(SEXP wrappedFixedEffectsSEXP, SEXP indicatorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type wrappedFixedEffects(wrappedFixedEffectsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type indicators(indicatorsSEXP);
    rcpp_result_gen = Rcpp::wrap(CheckComponents(wrappedFixedEffects, indicators));
    return rcpp_result_gen;
END_RCPP
}
// SolveFixedEffects
List SolveFixedEffects(arma::mat data, SEXP wrappedFixedEffects, std::size_t coreNum);
RcppExport SEXP _fastplm_SolveFixedEffects(SEXP dataSEXP, SEXP wrappedFixedEffectsSEXP, SEXP coreNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wrappedFixedEffects(wrappedFixedEffectsSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type coreNum(coreNumSEXP);
    rcpp_result_gen = Rcpp::wrap(SolveFixedEffects(data, wrappedFixedEffects, coreNum));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_fastplm_CreateFixedEffects", (DL_FUNC) &_fastplm_CreateFixedEffects, 6},
    {"_fastplm_ContainMultipleComponents", (DL_FUNC) &_fastplm_ContainMultipleComponents, 1},
    {"_fastplm_CheckComponents", (DL_FUNC) &_fastplm_CheckComponents, 2},
    {"_fastplm_SolveFixedEffects", (DL_FUNC) &_fastplm_SolveFixedEffects, 3},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastplm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
