# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solveFE <- function(rawData, rawFixedEffects) {
    .Call('fastplm_solveFE', PACKAGE = 'fastplm', rawData, rawFixedEffects)
}

solveGP <- function(Y, X, tois, iots, isBalanced) {
    .Call('fastplm_solveGP', PACKAGE = 'fastplm', Y, X, tois, iots, isBalanced)
}

