# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateFixedEffects <- function(levelCounts, indsR, simpleEffects, complexEffects, complexInfluences, wrappedWeights) {
    .Call(`_fastplm_CreateFixedEffects`, levelCounts, indsR, simpleEffects, complexEffects, complexInfluences, wrappedWeights)
}

ContainMultipleComponents <- function(wrappedFixedEffects) {
    .Call(`_fastplm_ContainMultipleComponents`, wrappedFixedEffects)
}

CheckComponents <- function(wrappedFixedEffects, indicators) {
    .Call(`_fastplm_CheckComponents`, wrappedFixedEffects, indicators)
}

SolveFixedEffects <- function(data, wrappedFixedEffects, coreNum = 1L) {
    .Call(`_fastplm_SolveFixedEffects`, data, wrappedFixedEffects, coreNum)
}

